# DEVELOP YML (DEFAULT)
# command: docker-compose build
version: '3.8'

services:
  flutter:
    container_name: flutter
    image: flutter
    build:
      # コンテキストをリポジトリのルートディレクトリに指定
      context: ../../
      dockerfile: ./provisioning/docker/flutter/Dockerfile
      args:
        # Dockerfile内でARGしている変数に.envに定義した値を代入。
        - ubuntu_version=${UBUNTU_VERSION}
        - timezone=${TIMEZONE}
        - web_server_port=${WEB_SERVER_PORT}
        - app_code_path_container=${APP_CODE_PATH_CONTAINER}
    env_file: .env
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
      - ~/.gitconfig:/home/root/.gitconfig
      - ~/.Xauthority:/root/.Xauthority
    ports:
      - "${WEB_SERVER_PORT}:${WEB_SERVER_PORT}"
    tty: true
